minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
shellEmulator: true

overrides:
  markdown-it@: 15.0.1

allowBuilds:
  esbuild: true
  simple-git-hooks: true
  vue-demi: true
  workerd: true
