/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/Button.vue')['default']
    DefaultLayout: typeof import('./layouts/DefaultLayout.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    ILucideMenu: typeof import('~icons/lucide/menu')['default']
    ILucideMoon: typeof import('~icons/lucide/moon')['default']
    ILucideSearch: typeof import('~icons/lucide/search')['default']
    ILucideSun: typeof import('~icons/lucide/sun')['default']
    ILucideX: typeof import('~icons/lucide/x')['default']
    Link: typeof import('./components/ui/Link.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
